-- Schema definition for core conformance entities (Oracle)
-- data-model.md §1 & §2

-- 1. Country (kế thừa từ corvus_conf)
CREATE TABLE country (
  country_id   NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country      VARCHAR2(50) NOT NULL,
  iso_code     CHAR(2),
  last_update  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
COMMENT ON TABLE country IS 'Bảng quốc gia dùng cho conformance';
COMMENT ON COLUMN country.iso_code IS 'ISO 3166-1 alpha-2';
CREATE UNIQUE INDEX country_name_uq ON country (country);

-- 2. City (kế thừa từ corvus_conf)
CREATE TABLE city (
  city_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id NUMBER(5) NOT NULL,
  city       VARCHAR2(50) NOT NULL,
  note       CLOB,
  CONSTRAINT fk_city_country FOREIGN KEY (country_id) REFERENCES country (country_id) ON DELETE CASCADE
);
CREATE INDEX city_country_idx ON city (country_id);

-- 3. "order details" (quoting check: tên có dấu cách, unicode, từ khoá SQL)
CREATE TABLE "order details" (
  id          NUMBER(10) PRIMARY KEY,
  "sản lượng" NUMBER(20,4),
  "select"    CLOB
);

-- 4. types_probe (kiểm tra kiểu dữ liệu đặc thù, number, clob, raw, timestamptz)
CREATE TABLE types_probe (
  id          NUMBER(10) PRIMARY KEY,
  big_val     NUMBER(19),
  numeric_val NUMBER(30,10),
  bool_val    NUMBER(1),
  text_null   VARCHAR2(4000),
  text_empty  VARCHAR2(4000),
  json_val    CLOB,
  bytes_val   RAW(2000),
  ts_val      TIMESTAMP WITH TIME ZONE
);

-- 5. city_view (view join cơ bản)
CREATE OR REPLACE VIEW city_view AS
  SELECT c.city_id, c.city, n.country
  FROM city c
  JOIN country n ON n.country_id = c.country_id;
