-- Dev environment extensions for corvus_dev (Oracle)
-- data-model.md §2, FR-009, FR-010, SR-004

-- 6. Customer (thực thể nghiệp vụ mở rộng)
CREATE TABLE customer (
  customer_id  NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id   NUMBER(5),
  email        VARCHAR2(100) NOT NULL,
  full_name    VARCHAR2(100) NOT NULL,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  is_active    NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT customer_email_uq UNIQUE (email),
  CONSTRAINT fk_customer_country FOREIGN KEY (country_id) REFERENCES country (country_id) ON DELETE SET NULL
);
CREATE INDEX customer_country_idx ON customer (country_id);

-- 7. order_log (bảng chứa ~100k dòng mẫu)
CREATE TABLE order_log (
  order_log_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  NUMBER(10),
  amount       NUMBER(12,2) NOT NULL,
  status       VARCHAR2(20) NOT NULL,
  placed_at    TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_order_log_customer FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);
CREATE INDEX order_log_customer_idx ON order_log (customer_id);
CREATE INDEX order_log_placed_at_idx ON order_log (placed_at);
CREATE INDEX order_log_status_idx ON order_log (status);

-- 8. customer_summary (view tổng hợp có aggregate)
CREATE OR REPLACE VIEW customer_summary AS
  SELECT
    c.customer_id,
    c.full_name,
    c.email,
    co.country,
    COUNT(o.order_log_id) AS total_orders,
    COALESCE(SUM(o.amount), 0) AS total_spent
  FROM customer c
  LEFT JOIN country co ON co.country_id = c.country_id
  LEFT JOIN order_log o ON o.customer_id = c.customer_id
  GROUP BY c.customer_id, c.full_name, c.email, co.country;

-- 9. fn_customer_total (stored routine)
CREATE OR REPLACE FUNCTION fn_customer_total(p_customer_id IN NUMBER)
RETURN NUMBER
IS
  v_total NUMBER(12,2);
BEGIN
  SELECT COALESCE(SUM(amount), 0) INTO v_total FROM order_log WHERE customer_id = p_customer_id;
  RETURN v_total;
END;
/

-- 10. trg_order_log_touch (trigger)
CREATE OR REPLACE TRIGGER trg_order_log_touch
BEFORE INSERT ON order_log
FOR EACH ROW
BEGIN
  IF :NEW.placed_at IS NULL THEN
    :NEW.placed_at := SYSTIMESTAMP;
  END IF;
END;
/

-- 11. corvus_env_marker (dấu hiệu môi trường phát triển & chốt an toàn SR-005, FR-012)
CREATE TABLE corvus_env_marker (
  "key"        VARCHAR2(50) PRIMARY KEY,
  "value"      VARCHAR2(255) NOT NULL,
  seeded_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  seed_version VARCHAR2(50) NOT NULL
);

-- Seed customer data (SR-004: fake data only, @example.invalid)
INSERT INTO customer (customer_id, country_id, email, full_name, created_at, is_active)
VALUES (1, 1, 'customer0001@example.invalid', 'Nguyen Van A', TIMESTAMP '2026-01-01 08:00:00 UTC', 1);
INSERT INTO customer (customer_id, country_id, email, full_name, created_at, is_active)
VALUES (2, 1, 'customer0002@example.invalid', 'Tran Thi B', TIMESTAMP '2026-01-02 09:30:00 UTC', 1);
INSERT INTO customer (customer_id, country_id, email, full_name, created_at, is_active)
VALUES (3, 2, 'customer0003@example.invalid', 'Kenji Sato', TIMESTAMP '2026-01-03 10:15:00 UTC', 1);
INSERT INTO customer (customer_id, country_id, email, full_name, created_at, is_active)
VALUES (4, 2, 'customer0004@example.invalid', 'Yuki Tanaka', TIMESTAMP '2026-01-04 11:00:00 UTC', 0);
INSERT INTO customer (customer_id, country_id, email, full_name, created_at, is_active)
VALUES (5, 3, 'customer0005@example.invalid', 'Lucas Silva', TIMESTAMP '2026-01-05 12:45:00 UTC', 1);
INSERT INTO customer (customer_id, country_id, email, full_name, created_at, is_active)
VALUES (6, 3, 'customer0006@example.invalid', 'Beatriz Souza', TIMESTAMP '2026-01-06 14:20:00 UTC', 1);

-- Seed marker
INSERT INTO corvus_env_marker ("key", "value", seeded_at, seed_version)
VALUES ('corvus_dev', 'ready', TIMESTAMP '2026-01-01 00:00:00 UTC', '1.0.0');

COMMIT;
