-- Seed ~1,000,000 deterministic rows into order_log_bulk on-demand (Oracle)
-- FR-011a, FR-011b, data-model.md §2

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE order_log_bulk (
      order_log_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer_id  NUMBER(10),
      amount       NUMBER(12,2) NOT NULL,
      status       VARCHAR2(20) NOT NULL,
      placed_at    TIMESTAMP WITH TIME ZONE NOT NULL,
      CONSTRAINT fk_order_log_bulk_cust FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

INSERT INTO order_log_bulk (order_log_id, customer_id, amount, status, placed_at)
SELECT
  LEVEL AS order_log_id,
  MOD(LEVEL - 1, 10) + 1 AS customer_id,
  ROUND((MOD(LEVEL * 23, 100000) + 500) / 100, 2) AS amount,
  CASE MOD(LEVEL, 4)
    WHEN 0 THEN 'completed'
    WHEN 1 THEN 'pending'
    WHEN 2 THEN 'shipped'
    ELSE 'cancelled'
  END AS status,
  TIMESTAMP '2026-01-01 00:00:00 UTC' + NUMTODSINTERVAL(LEVEL * 10, 'SECOND') AS placed_at
FROM DUAL
CONNECT BY LEVEL <= 1000000;

COMMIT;
