import type { CapabilitySet } from '@corvus/contract'

export const MYSQL_CAPABILITIES: CapabilitySet = {
  hierarchy: {
    hasCatalogs: false,
    hasSchemas: false,
  },
  objects: {
    table: true,
    view: true,
    materializedView: false,
    procedure: true,
    function: true,
    package: false,
    trigger: true,
    sequence: false,
    index: true,
    domain: false,
    type: false,
    event: true,
    collection: false,
    keyspace: false,
  },
  sql: {
    parameterStyle: 'question',
    identifierQuote: '`',
    limitSyntax: 'limit-offset',
    maxIdentifierLength: 64,
    caseSensitivity: 'platform',
    cte: true,
    windowFunctions: true,
    returning: false,
    upsert: 'on-duplicate-key',
  },
  exec: {
    streamingCursor: true,
    multipleStatements: true,
    multipleResultSets: true,
    cancelStatement: true,
    explain: true,
    explainAnalyze: true,
    preparedStatements: true,
  },
  tx: {
    supported: true,
    savepoints: true,
    ddlTransactional: false,
    isolationLevels: 4,
  },
  tools: {
    logicalBackup: true,
    physicalBackup: true,
    userManagement: true,
    roleManagement: true,
    processMonitor: true,
    serverVariables: true,
    dataGeneration: true,
    profiling: true,
  },
}
