import type { CapabilitySet } from '@corvus/contract'

export const MONGO_CAPABILITIES: CapabilitySet = {
  hierarchy: {
    hasCatalogs: false,
    hasSchemas: false,
  },
  objects: {
    table: false,
    view: true,
    materializedView: false,
    procedure: false,
    function: false,
    package: false,
    trigger: false,
    sequence: false,
    index: true,
    domain: false,
    type: false,
    event: false,
    collection: true,
    keyspace: false,
  },
  sql: {
    supported: false,
    parameterStyle: 'dollar',
    identifierQuote: '"',
    limitSyntax: 'limit-offset',
    maxIdentifierLength: 128,
    caseSensitivity: 'insensitive',
    cte: false,
    windowFunctions: false,
    returning: false,
    upsert: 'none',
  },
  exec: {
    streamingCursor: true,
    multipleStatements: false,
    multipleResultSets: false,
    cancelStatement: true,
    explain: true,
    explainAnalyze: true,
    preparedStatements: false,
  },
  tx: {
    supported: true,
    savepoints: false,
    ddlTransactional: false,
    isolationLevels: 1,
  },
  tools: {
    logicalBackup: true,
    physicalBackup: false,
    userManagement: true,
    roleManagement: true,
    processMonitor: true,
    serverVariables: false,
    dataGeneration: true,
    profiling: true,
  },
}
