import type { CapabilitySet } from '@corvus/contract'

export const SQLITE_CAPABILITIES: CapabilitySet = {
  hierarchy: {
    hasCatalogs: false,
    hasSchemas: false,
  },
  objects: {
    table: true,
    view: true,
    materializedView: false,
    procedure: false,
    function: false,
    package: false,
    trigger: true,
    sequence: false,
    index: true,
    domain: false,
    type: false,
    event: false,
    collection: false,
    keyspace: false,
  },
  sql: {
    parameterStyle: 'question',
    identifierQuote: '"',
    limitSyntax: 'limit-offset',
    maxIdentifierLength: 1000000,
    caseSensitivity: 'insensitive',
    cte: true,
    windowFunctions: true,
    returning: true,
    upsert: 'on-conflict',
  },
  exec: {
    streamingCursor: true,
    multipleStatements: true,
    multipleResultSets: false,
    cancelStatement: true,
    explain: true,
    explainAnalyze: false,
    preparedStatements: true,
  },
  tx: {
    supported: true,
    savepoints: true,
    ddlTransactional: true,
    isolationLevels: 2,
  },
  tools: {
    logicalBackup: true,
    physicalBackup: true,
    userManagement: false,
    roleManagement: false,
    processMonitor: false,
    serverVariables: true,
    dataGeneration: true,
    profiling: true,
  },
}
