import type { CapabilitySet } from '@corvus/contract'

export const POSTGRES_CAPABILITIES: CapabilitySet = {
  hierarchy: {
    hasCatalogs: true,
    hasSchemas: true,
  },
  objects: {
    table: true,
    view: true,
    materializedView: true,
    procedure: true,
    function: true,
    package: false,
    trigger: true,
    sequence: true,
    index: true,
    domain: true,
    type: true,
    event: false,
    collection: false,
    keyspace: false,
  },
  sql: {
    parameterStyle: 'dollar',
    identifierQuote: '"',
    limitSyntax: 'limit-offset',
    maxIdentifierLength: 63,
    caseSensitivity: 'lower',
    cte: true,
    windowFunctions: true,
    returning: true,
    upsert: 'on-conflict',
  },
  exec: {
    streamingCursor: true,
    multipleStatements: true,
    multipleResultSets: true,
    cancelStatement: true,
    explain: true,
    explainAnalyze: true,
    preparedStatements: true,
  },
  tx: {
    supported: true,
    savepoints: true,
    ddlTransactional: true,
    isolationLevels: 4,
  },
  tools: {
    logicalBackup: true,
    physicalBackup: true,
    userManagement: true,
    roleManagement: true,
    processMonitor: true,
    serverVariables: true,
    dataGeneration: true,
    profiling: true,
  },
}
