/**
 * Schema mẫu dùng chung cho conformance suite.
 *
 * Cố tình chứa các trường hợp dễ làm driver sai:
 *   - tên có unicode, dấu cách, và từ khoá SQL  → kiểm quoting (security.md TM-6)
 *   - NULL và chuỗi rỗng cùng tồn tại           → kiểm phân biệt (SPEC-03 FR-03.03)
 *   - bigint vượt 2^53                          → kiểm không mất chính xác
 *   - FK nhiều cột, index unique và thường
 */
export const CONFORMANCE_SCHEMA = 'corvus_conf'

export const POSTGRES_SETUP_SQL = `
CREATE SCHEMA IF NOT EXISTS ${CONFORMANCE_SCHEMA};

CREATE TABLE ${CONFORMANCE_SCHEMA}.country (
  country_id   smallint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country      varchar(50)  NOT NULL,
  iso_code     char(2),
  last_update  timestamptz  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  ${CONFORMANCE_SCHEMA}.country IS 'Bảng quốc gia dùng cho conformance';
COMMENT ON COLUMN ${CONFORMANCE_SCHEMA}.country.iso_code IS 'ISO 3166-1 alpha-2';
CREATE UNIQUE INDEX country_name_uq ON ${CONFORMANCE_SCHEMA}.country (country);

CREATE TABLE ${CONFORMANCE_SCHEMA}.city (
  city_id     integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id  smallint    NOT NULL REFERENCES ${CONFORMANCE_SCHEMA}.country(country_id) ON DELETE CASCADE,
  city        varchar(50) NOT NULL,
  note        text
);
CREATE INDEX city_country_idx ON ${CONFORMANCE_SCHEMA}.city (country_id);

-- Ten object kho: dau cach, unicode, va tu khoa SQL.
CREATE TABLE ${CONFORMANCE_SCHEMA}."order details" (
  id integer PRIMARY KEY,
  "sản lượng" numeric(20,4),
  "select" text
);

CREATE VIEW ${CONFORMANCE_SCHEMA}.city_view AS
  SELECT c.city_id, c.city, n.country FROM ${CONFORMANCE_SCHEMA}.city c
  JOIN ${CONFORMANCE_SCHEMA}.country n USING (country_id);

CREATE TABLE ${CONFORMANCE_SCHEMA}.types_probe (
  id            integer PRIMARY KEY,
  big_val       bigint,
  numeric_val   numeric(30,10),
  bool_val      boolean,
  text_null     text,
  text_empty    text,
  json_val      jsonb,
  bytes_val     bytea,
  ts_val        timestamptz
);

INSERT INTO ${CONFORMANCE_SCHEMA}.country (country_id, country, iso_code) VALUES
  (1, 'Việt Nam', 'VN'), (2, 'Japan', 'JP'), (3, 'Brazil', 'BR');

INSERT INTO ${CONFORMANCE_SCHEMA}.city (city_id, country_id, city, note) VALUES
  (1, 1, 'Hà Nội', NULL), (2, 1, 'Đà Nẵng', ''), (3, 2, 'Tokyo', 'thủ đô');

INSERT INTO ${CONFORMANCE_SCHEMA}.types_probe
  (id, big_val, numeric_val, bool_val, text_null, text_empty, json_val, bytes_val, ts_val) VALUES
  (1, 9223372036854775807, 12345678901234567890.0123456789, true,
   NULL, '', '{"a":[1,2,3]}'::jsonb, '\xdeadbeef'::bytea, '2026-08-18T09:00:00Z');
`
