import type { Command } from '../types'

export const DIAGRAM_COMMANDS: readonly Command[] = [
  {
    id: 'qb.removeTable',
    labelKey: 'qbRemoveTable',
    surfaces: ['ctx-query-builder'],
    targets: ['canvas-node'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'qb.tableProperties',
    labelKey: 'qbTableProperties',
    surfaces: ['ctx-query-builder'],
    targets: ['canvas-node'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
    },
    write: 'none',
    rpc: ['introspect.tableMeta'],
    async run() {},
  },
  {
    id: 'qb.editJoin',
    labelKey: 'qbEditJoin',
    surfaces: ['ctx-query-builder'],
    targets: ['canvas-edge'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'qb.deleteJoin',
    labelKey: 'qbDeleteJoin',
    surfaces: ['ctx-query-builder'],
    targets: ['canvas-edge'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'qb.addTable',
    labelKey: 'qbAddTable',
    surfaces: ['ctx-query-builder'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
    },
    write: 'none',
    rpc: ['introspect.objects'],
    async run() {},
  },
  {
    id: 'qb.clearCanvas',
    labelKey: 'qbClearCanvas',
    surfaces: ['ctx-query-builder'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'er.focusNode',
    labelKey: 'erFocusNode',
    surfaces: ['ctx-er-diagram'],
    targets: ['canvas-node'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'er.hideTable',
    labelKey: 'erHideTable',
    surfaces: ['ctx-er-diagram'],
    targets: ['canvas-node'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'er.inspectRelationship',
    labelKey: 'erInspectRel',
    surfaces: ['ctx-er-diagram'],
    targets: ['canvas-edge'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
    },
    write: 'none',
    rpc: ['introspect.tableMeta'],
    async run() {},
  },
  {
    id: 'er.autoLayout',
    labelKey: 'erAutoLayout',
    surfaces: ['ctx-er-diagram'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'er.resetZoom',
    labelKey: 'erResetZoom',
    surfaces: ['ctx-er-diagram'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
]
