import type { Command } from '../types'

export const GRID_COMMANDS: readonly Command[] = [
  {
    id: 'grid.copyCell',
    labelKey: 'copyCellValue',
    surfaces: ['ctx-data-grid'],
    targets: ['cell'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'grid.editCell',
    labelKey: 'editCellValue',
    surfaces: ['ctx-data-grid'],
    targets: ['cell'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'grid.setNull',
    labelKey: 'setCellNull',
    surfaces: ['ctx-data-grid'],
    targets: ['cell'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
      permission: 'write',
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'grid.deleteRow',
    labelKey: 'deleteGridRow',
    surfaces: ['ctx-data-grid'],
    targets: ['row-header'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
      permission: 'write',
    },
    write: 'preview-required',
    rpc: ['ddl.previewTable', 'ddl.applyTable'],
    async run() {},
  },
  {
    id: 'grid.sortAsc',
    labelKey: 'sortAscending',
    surfaces: ['ctx-data-grid'],
    targets: ['column-header'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'grid.sortDesc',
    labelKey: 'sortDescending',
    surfaces: ['ctx-data-grid'],
    targets: ['column-header'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'grid.addRow',
    labelKey: 'addGridRow',
    surfaces: ['ctx-data-grid'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
      permission: 'write',
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'grid.refresh',
    labelKey: 'refreshList',
    surfaces: ['ctx-data-grid'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
    },
    write: 'none',
    rpc: ['query.execute'],
    async run() {},
  },
]
