import type { Command } from '../types'

export const SHELL_COMMANDS: readonly Command[] = [
  {
    id: 'tab.close',
    labelKey: 'closeActiveTab',
    surfaces: ['ctx-tab-bar'],
    targets: ['tab'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'tab.closeOthers',
    labelKey: 'closeOtherTabs',
    surfaces: ['ctx-tab-bar'],
    targets: ['tab'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'tab.duplicate',
    labelKey: 'duplicateActiveTab',
    surfaces: ['ctx-tab-bar'],
    targets: ['tab'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'toolbar.customize',
    labelKey: 'customizeToolbar',
    surfaces: ['ctx-toolbar'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'toolbar.reset',
    labelKey: 'resetToolbar',
    surfaces: ['ctx-toolbar'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'snippet.insert',
    labelKey: 'insertSnippet',
    surfaces: ['ctx-snippet'],
    targets: ['snippet'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'snippet.edit',
    labelKey: 'editSnippet',
    surfaces: ['ctx-snippet'],
    targets: ['snippet'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'snippet.new',
    labelKey: 'newSnippet',
    surfaces: ['ctx-snippet'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'job.runNow',
    labelKey: 'runJobNow',
    surfaces: ['ctx-job-list'],
    targets: ['job'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
    },
    write: 'none',
    rpc: ['schedule.runNow'],
    async run(ctx) {
      if (ctx.active.selection.primaryTarget) {
        await ctx.client.request('schedule.runNow', { scheduleId: ctx.active.selection.primaryTarget })
      }
    },
  },
  {
    id: 'job.edit',
    labelKey: 'editJob',
    surfaces: ['ctx-job-list'],
    targets: ['job'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'job.delete',
    labelKey: 'deleteJob',
    surfaces: ['ctx-job-list'],
    targets: ['job'],
    cardinality: 'multi',
    availability: {
      needsConnection: true,
      permission: 'write',
    },
    write: 'preview-required',
    rpc: ['ddl.previewTable', 'ddl.applyTable'],
    async run() {},
  },
  {
    id: 'job.create',
    labelKey: 'createJob',
    surfaces: ['ctx-job-list'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: ['schedule.create'],
    async run() {},
  },
  {
    id: 'diff.revert',
    labelKey: 'diffRevert',
    surfaces: ['ctx-diff'],
    targets: ['diff-item'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
      permission: 'write',
    },
    write: 'preview-required',
    rpc: ['ddl.previewTable', 'ddl.applyTable'],
    async run() {},
  },
  {
    id: 'diff.inspect',
    labelKey: 'diffInspect',
    surfaces: ['ctx-diff'],
    targets: ['diff-item'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'diff.refresh',
    labelKey: 'diffRefresh',
    surfaces: ['ctx-diff'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
    },
    write: 'none',
    rpc: ['query.execute'],
    async run() {},
  },
]
