import type { Command } from '../types'

export const SQL_COMMANDS: readonly Command[] = [
  {
    id: 'sql.runSelection',
    labelKey: 'runSqlSelection',
    surfaces: ['ctx-sql-editor'],
    targets: ['editor-selection'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
    },
    write: 'none',
    rpc: ['query.execute'],
    async run() {},
  },
  {
    id: 'sql.formatSelection',
    labelKey: 'formatSqlSelection',
    surfaces: ['ctx-sql-editor'],
    targets: ['editor-selection'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'sql.runAll',
    labelKey: 'runAllSql',
    surfaces: ['ctx-sql-editor'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
    },
    write: 'none',
    rpc: ['query.execute'],
    async run() {},
  },
  {
    id: 'sql.clearEditor',
    labelKey: 'clearSqlEditor',
    surfaces: ['ctx-sql-editor'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: false,
    },
    write: 'none',
    rpc: [],
    async run() {},
  },
  {
    id: 'sql.txBegin',
    labelKey: 'txBegin',
    surfaces: ['ctx-sql-editor'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
      permission: 'write',
    },
    write: 'none',
    rpc: ['tx.begin'],
    async run() {},
  },
  {
    id: 'sql.txCommit',
    labelKey: 'txCommit',
    surfaces: ['ctx-sql-editor'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
      permission: 'write',
    },
    write: 'none',
    rpc: ['tx.commit'],
    async run() {},
  },
  {
    id: 'sql.txRollback',
    labelKey: 'txRollback',
    surfaces: ['ctx-sql-editor'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
      permission: 'write',
    },
    write: 'none',
    rpc: ['tx.rollback'],
    async run() {},
  },
  {
    id: 'sql.txStatus',
    labelKey: 'txStatus',
    surfaces: ['ctx-sql-editor'],
    targets: ['empty'],
    cardinality: 'single',
    availability: {
      needsConnection: true,
    },
    write: 'none',
    rpc: ['tx.status'],
    async run() {},
  },
]
