-- Schema definition for core conformance entities (PostgreSQL)
-- data-model.md §1 & §2

CREATE SCHEMA IF NOT EXISTS corvus_dev;

-- 1. Country (kế thừa từ corvus_conf)
CREATE TABLE corvus_dev.country (
  country_id   smallint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country      varchar(50)  NOT NULL,
  iso_code     char(2),
  last_update  timestamptz  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  corvus_dev.country IS 'Bảng quốc gia dùng cho conformance';
COMMENT ON COLUMN corvus_dev.country.iso_code IS 'ISO 3166-1 alpha-2';
CREATE UNIQUE INDEX country_name_uq ON corvus_dev.country (country);

-- 2. City (kế thừa từ corvus_conf)
CREATE TABLE corvus_dev.city (
  city_id     integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id  smallint    NOT NULL REFERENCES corvus_dev.country(country_id) ON DELETE CASCADE,
  city        varchar(50) NOT NULL,
  note        text
);
CREATE INDEX city_country_idx ON corvus_dev.city (country_id);

-- 3. "order details" (quoting check: tên có dấu cách, unicode, từ khoá SQL)
CREATE TABLE corvus_dev."order details" (
  id integer PRIMARY KEY,
  "sản lượng" numeric(20,4),
  "select" text
);

-- 4. types_probe (kiểm tra kiểu dữ liệu đặc thù, bigint > 2^53, numeric, jsonb, bytea)
CREATE TABLE corvus_dev.types_probe (
  id            integer PRIMARY KEY,
  big_val       bigint,
  numeric_val   numeric(30,10),
  bool_val      boolean,
  text_null     text,
  text_empty    text,
  json_val      jsonb,
  bytes_val     bytea,
  ts_val        timestamptz
);

-- 5. city_view (view join cơ bản)
CREATE OR REPLACE VIEW corvus_dev.city_view AS
  SELECT c.city_id, c.city, n.country
  FROM corvus_dev.city c
  JOIN corvus_dev.country n USING (country_id);
