-- Dev environment extensions for corvus_dev (PostgreSQL)
-- data-model.md §2, FR-009, FR-010, SR-004

-- 6. Customer (thực thể nghiệp vụ mở rộng)
CREATE TABLE IF NOT EXISTS corvus_dev.customer (
  customer_id  integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id   smallint     REFERENCES corvus_dev.country(country_id) ON DELETE SET NULL,
  email        varchar(100) NOT NULL,
  full_name    varchar(100) NOT NULL,
  created_at   timestamptz  NOT NULL DEFAULT '2026-01-01 00:00:00+00',
  is_active    boolean      NOT NULL DEFAULT true
);
CREATE UNIQUE INDEX IF NOT EXISTS customer_email_uq ON corvus_dev.customer (email);
CREATE INDEX IF NOT EXISTS customer_country_idx ON corvus_dev.customer (country_id);

-- 7. order_log (bảng chứa ~100k dòng mẫu)
CREATE TABLE IF NOT EXISTS corvus_dev.order_log (
  order_log_id integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  integer       REFERENCES corvus_dev.customer(customer_id) ON DELETE CASCADE,
  amount       numeric(12,2) NOT NULL,
  status       varchar(20)   NOT NULL,
  placed_at    timestamptz   NOT NULL
);
CREATE INDEX IF NOT EXISTS order_log_customer_idx ON corvus_dev.order_log (customer_id);
CREATE INDEX IF NOT EXISTS order_log_placed_at_idx ON corvus_dev.order_log (placed_at);
CREATE INDEX IF NOT EXISTS order_log_status_idx ON corvus_dev.order_log (status);

-- 8. customer_summary (view tổng hợp có aggregate)
CREATE OR REPLACE VIEW corvus_dev.customer_summary AS
  SELECT
    c.customer_id,
    c.full_name,
    c.email,
    co.country,
    COUNT(o.order_log_id) AS total_orders,
    COALESCE(SUM(o.amount), 0) AS total_spent
  FROM corvus_dev.customer c
  LEFT JOIN corvus_dev.country co ON co.country_id = c.country_id
  LEFT JOIN corvus_dev.order_log o ON o.customer_id = c.customer_id
  GROUP BY c.customer_id, c.full_name, c.email, co.country;

-- 9. fn_customer_total (stored routine)
CREATE OR REPLACE FUNCTION corvus_dev.fn_customer_total(p_customer_id integer)
RETURNS numeric AS $$
  SELECT COALESCE(SUM(amount), 0)
  FROM corvus_dev.order_log
  WHERE customer_id = p_customer_id;
$$ LANGUAGE sql STABLE;

-- 10. trg_order_log_touch (trigger function & trigger)
CREATE OR REPLACE FUNCTION corvus_dev.fn_order_log_touch()
RETURNS trigger AS $$
BEGIN
  IF NEW.placed_at IS NULL THEN
    NEW.placed_at := '2026-01-01 00:00:00+00'::timestamptz;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_order_log_touch ON corvus_dev.order_log;
CREATE TRIGGER trg_order_log_touch
  BEFORE INSERT OR UPDATE ON corvus_dev.order_log
  FOR EACH ROW
  EXECUTE FUNCTION corvus_dev.fn_order_log_touch();

-- 11. corvus_env_marker (dấu hiệu môi trường phát triển & chốt an toàn SR-005, FR-012)
CREATE TABLE IF NOT EXISTS corvus_dev.corvus_env_marker (
  key          varchar(50)  PRIMARY KEY,
  value        varchar(255) NOT NULL,
  seeded_at    timestamptz  NOT NULL DEFAULT '2026-01-01 00:00:00+00',
  seed_version varchar(50)  NOT NULL
);

-- Seed customer data (SR-004: fake data only, @example.invalid)
INSERT INTO corvus_dev.customer (customer_id, country_id, email, full_name, created_at, is_active) VALUES
  (1, 1, 'customer0001@example.invalid', 'Nguyen Van A', '2026-01-01 08:00:00+00', true),
  (2, 1, 'customer0002@example.invalid', 'Tran Thi B', '2026-01-02 09:30:00+00', true),
  (3, 2, 'customer0003@example.invalid', 'Kenji Sato', '2026-01-03 10:15:00+00', true),
  (4, 2, 'customer0004@example.invalid', 'Yuki Tanaka', '2026-01-04 11:00:00+00', false),
  (5, 3, 'customer0005@example.invalid', 'Lucas Silva', '2026-01-05 12:45:00+00', true),
  (6, 3, 'customer0006@example.invalid', 'Beatriz Souza', '2026-01-06 14:20:00+00', true)
ON CONFLICT (customer_id) DO NOTHING;

-- Seed marker
INSERT INTO corvus_dev.corvus_env_marker (key, value, seeded_at, seed_version) VALUES
  ('corvus_dev', 'ready', '2026-01-01 00:00:00+00', '1.0.0')
ON CONFLICT (key) DO UPDATE SET
  value = EXCLUDED.value,
  seeded_at = EXCLUDED.seeded_at,
  seed_version = EXCLUDED.seed_version;
