-- Seed ~1,000,000 deterministic rows into order_log_bulk on-demand (PostgreSQL)
-- FR-011a, FR-011b, data-model.md §2

CREATE TABLE IF NOT EXISTS corvus_dev.order_log_bulk (
  order_log_id integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  integer       REFERENCES corvus_dev.customer(customer_id) ON DELETE CASCADE,
  amount       numeric(12,2) NOT NULL,
  status       varchar(20)   NOT NULL,
  placed_at    timestamptz   NOT NULL
);
CREATE INDEX IF NOT EXISTS order_log_bulk_customer_idx ON corvus_dev.order_log_bulk (customer_id);
CREATE INDEX IF NOT EXISTS order_log_bulk_placed_at_idx ON corvus_dev.order_log_bulk (placed_at);

INSERT INTO corvus_dev.order_log_bulk (order_log_id, customer_id, amount, status, placed_at)
SELECT
  s AS order_log_id,
  ((s - 1) % 10) + 1 AS customer_id,
  (((s * 23) % 100000) + 500)::numeric / 100 AS amount,
  CASE (s % 4)
    WHEN 0 THEN 'completed'
    WHEN 1 THEN 'pending'
    WHEN 2 THEN 'shipped'
    ELSE 'cancelled'
  END AS status,
  '2026-01-01 00:00:00+00'::timestamptz + (s * interval '10 seconds') AS placed_at
FROM generate_series(1, 1000000) AS s
ON CONFLICT (order_log_id) DO NOTHING;
